#!/usr/local/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
exportPATH

SERVER="$(hostname)"
IP=$(host"$(whoami).valuehost.ru" | cut -f4 -d' ')
DATE=$(date '+%m-%d-%Y')
TIME=$(date '+%H:%M')
# задаём исключения (например, для усердных админов сайтов)
# (можно указывать IP-адрес или кусок запроса админа к скрипту админки)
EXCEPT="option=com|46.72.47.31|89.111.144.46|94.241.23.156"
# создаём папку и файл для записи ежедневных логов отправки уведомлений
mkdir ~/abuse_logs > /dev/null 2>&1
mkdir ~/abuse_logs/$DATE > /dev/null 2>&1
touch ~/abuse_logs/$DATE/abuse_noticed.lst

# выбираем в логах сервера POST-запросы в админки, среди них выбираем IP, от которых таких запросов было > 50 за полчаса
cat /var/log/nginx-monitor.log | grep -E 'POST /administrator/index.php|POST /wp-login.php' | grep -E -v $EXCEPT |
cut -f1 -d' ' | sort | uniq -c | sort -r | head -5 | sed 's/^ *//g' | 
# > 50 попыток
grep -E '^5[0-9]{1,}|^6[0-9]{1,}|^7[0-9]{1,}|^8[0-9]{1,}|^9[0-9]{1,}|^1[0-9]{2,}|^2[0-9]{2,}|^3[0-9]{2,}|^4[0-9]{2,}' |
# > 30 попыток
#grep -E '^3[0-9]{1,}|^4[0-9]{1,}|^5[0-9]{1,}|^6[0-9]{1,}|^7[0-9]{1,}|^8[0-9]{1,}|^9[0-9]{1,}|^1[0-9]{2,}|^2[0-9]{2,}' | 
cut -f2 -d' ' |

while read n ; do 
(
# находим адреса куда слать абузы
EMAIL=$(sh ~/abuse.sh $n)
# выводим общее кол-во попыток от этого IP, зафиксированных в ip_logs
COUNT_ALL=$(find ~/ip_logs -type f | xargs cat | grep $n | 
grep -E '[[:digit:]]{1,4} [[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}' | 
sed 's/^ *//g' | cut -f1 -d' ' | perl -ne '$a+=$_; END{ print " $a " }')
# количество попыток от этого IP в текущем логе
COUNT_RECENT=$(cat /var/log/nginx-monitor.log | grep -E 'POST /administrator/index.php|POST /wp-login.php' | grep -c $n)
# составляем тело письма
MAIL_BODY="$(echo -e "Greetings,

Valuehost abuse team like to inform you, that we have had mass bruteforce attempts 
to the Joomla / WordPress control panel on the our shared-hosting server $SERVER [$IP]
from your network, from IP address $n

During the last 30 minutes we recorded $COUNT_RECENT attempts like this:\n"

# как пример даём 5 записей из лога сервера..
cat /var/log/nginx-monitor.log | grep -E 'POST /administrator/index.php|POST /wp-login.php' | grep $n | tail -5 ; 
echo -e "\n"

# ..и общее кол-во попыток от этого IP, зафиксированных в ip_logs (если они были)
if [ "$COUNT_ALL" > 0 ]; then 
echo -e "Total number of this attempts that have been recorded previously at this server ($SERVER)[$IP]: $COUNT_ALL \n\n"
fi
echo -e "====

This message was sent automatically by ValueHost security system.
Yor e-mail address obtained from the public WhoIs services.
We are sorry for disturb if you have received this message by mistake.
Please contact us if your e-mail is not relevant to this IP-address or network. 

====

Thank you,

Valuehost abuse team

http://www.valuehost.ru
+7 (812) 313-29-08,
+7 (495) 540-52-24
E-mail: abuse@valuehost.ru"
)"

# проверяем, не писали ли мы уже сегодня абузу на этот IP
if [ "$(cat ~/abuse_logs/$DATE/abuse_noticed.lst | grep -c $n)" = "$(echo 0)" ]; then
    # проверяем наличие адреса для отправки абузы
    if [ "$EMAIL" = "$(echo "")" ]; then
   # если адрес не найден, то отправляем письмо мне
    (echo -e "${MAIL_BODY}") | mail -s "oops, IP $n has no abuse e-mail" mkotikov@yandex.ru
  else
   # если адрес есть - пишем на адрес и дублируем мне (#+ уведомляем меня, что адрес уведомлен) + делаем запись в лог отправки уведомлений
    (echo -e "From:abuse@valuehost.ru\nSubject:Mass bruteforce attemps from your network: IP $n\nTo:mkotikov@yandex.ru, $EMAIL" ; 
    echo -e "${MAIL_BODY}") | sendmail -t "mkotikov@yandex.ru, $EMAIL" ; 
#   echo -e "From:abuse@valuehost.ru\nSubject:abuse notice for $n was sent to $EMAIL from $SERVER\nTo:mkotikov@yandex.ru\nReport from $SERVER: $EMAIL noticed about $n" | sendmail -t mkotikov@yandex.ru ; 
    echo "$EMAIL noticed about $n at $DATE $TIME" >> ~/abuse_logs/$DATE/abuse_noticed.lst
  fi
else
  # а если уже писали - ничего не делаем
  sleep 1
fi
);
done;
