#!/usr/local/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
exportPATH

SERVER="$(hostname)"
IP=$(host"$(whoami).valuehost.ru" | cut -f4 -d' ')
DATE=$(date '+%m-%d-%Y')
TIME=$(date '+%H:%M')
# задаём исключения (например, для усердных админов сайтов)
# (можно указывать IP-адрес или кусок запроса админа к скрипту админки)
# Р·Р°РґР°С‘Рј РёСЃРєР»СЋС‡РµРЅРёСЏ (РЅР°РїСЂРёРјРµСЂ, РґР»СЏ СѓСЃРµСЂРґРЅС‹С… Р°РґРјРёРЅРѕРІ СЃР°Р№С‚РѕРІ)
# (РјРѕР¶РЅРѕ СѓРєР°Р·С‹РІР°С‚СЊ IP-Р°РґСЂРµСЃ РёР»Рё РєСѓСЃРѕРє Р·Р°РїСЂРѕСЃР° Р°РґРјРёРЅР° Рє СЃРєСЂРёРїС‚Сѓ Р°РґРјРёРЅРєРё)
EXCEPT="option=com|46.72.47.31|89.111.144.46|94.241.23.156"

# СЃРѕР·РґР°С‘Рј РїР°РїРєСѓ Рё С„Р°Р№Р» РґР»СЏ Р·Р°РїРёСЃРё РµР¶РµРґРЅРµРІРЅС‹С… Р»РѕРіРѕРІ РѕС‚РїСЂР°РІРєРё СѓРІРµРґРѕРјР»РµРЅРёР№
mkdir ~/abuse_logs > /dev/null 2>&1
mkdir ~/abuse_logs/$DATE > /dev/null 2>&1
touch ~/abuse_logs/$DATE/abuse_noticed.lst

# РІС‹Р±РёСЂР°РµРј РІ Р»РѕРіР°С… СЃРµСЂРІРµСЂР° POST-Р·Р°РїСЂРѕСЃС‹ РІ Р°РґРјРёРЅРєРё, СЃСЂРµРґРё РЅРёС… РІС‹Р±РёСЂР°РµРј IP, РѕС‚ РєРѕС‚РѕСЂС‹С… С‚Р°РєРёС… Р·Р°РїСЂРѕСЃРѕРІ Р±С‹Р»Рѕ > 50 Р·Р° РїРѕР»С‡Р°СЃР°
cat /var/log/nginx-monitor.log | grep -E 'POST /administrator/index.php|POST /wp-login.php' | grep -E -v $EXCEPT |
cut -f1 -d' ' | sort | uniq -c | sort -r | head -5 | sed 's/^ *//g' | 
# > 50 РїРѕРїС‹С‚РѕРє
grep -E '^5[0-9]{1,}|^6[0-9]{1,}|^7[0-9]{1,}|^8[0-9]{1,}|^9[0-9]{1,}|^1[0-9]{2,}|^2[0-9]{2,}|^3[0-9]{2,}|^4[0-9]{2,}' |
# > 30 РїРѕРїС‹С‚РѕРє
#grep -E '^3[0-9]{1,}|^4[0-9]{1,}|^5[0-9]{1,}|^6[0-9]{1,}|^7[0-9]{1,}|^8[0-9]{1,}|^9[0-9]{1,}|^1[0-9]{2,}|^2[0-9]{2,}' | 
cut -f2 -d' ' |

while read n ; do 
(
# РЅР°С…РѕРґРёРј Р°РґСЂРµСЃР° РєСѓРґР° СЃР»Р°С‚СЊ Р°Р±СѓР·С‹
EMAIL=$(sh ~/abuse.sh $n)
# РѕР±С‰РµРµ РєРѕР»-РІРѕ РїРѕРїС‹С‚РѕРє РѕС‚ СЌС‚РѕРіРѕ IP, Р·Р°С„РёРєСЃРёСЂРѕРІР°РЅРЅС‹С… РІ ip_logs
COUNT_ALL=$(find ~/ip_logs -type f | xargs cat | grep $n | 
grep -E '[[:digit:]]{1,4} [[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}' | 
sed 's/^ *//g' | cut -f1 -d' ' | perl -ne '$a+=$_; END{ print " $a " }')
# РєРѕР»РёС‡РµСЃС‚РІРѕ РїРѕРїС‹С‚РѕРє РѕС‚ СЌС‚РѕРіРѕ IP РІ С‚РµРєСѓС‰РµРј Р»РѕРіРµ
COUNT_RECENT=$(cat /var/log/nginx-monitor.log | grep -E 'POST /administrator/index.php|POST /wp-login.php' | grep -c $n)
# СЃРѕСЃС‚Р°РІР»СЏРµРј С‚РµР»Рѕ РїРёСЃСЊРјР°
MAIL_BODY="$(echo -e "Greetings,

Valuehost abuse team like to inform you, that we have had mass bruteforce attempts 
to the Joomla / WordPress control panel on the our shared-hosting server $SERVER [$IP]
from your network, from IP address $n

During the last 30 minutes we recorded $COUNT_RECENT attempts like this:\n"

# РєР°Рє РїСЂРёРјРµСЂ РґР°С‘Рј 5 Р·Р°РїРёСЃРµР№ РёР· Р»РѕРіР° СЃРµСЂРІРµСЂР°..
cat /var/log/nginx-monitor.log | grep -E 'POST /administrator/index.php|POST /wp-login.php' | grep $n | tail -5 ; 
echo -e "\n"

# ..Рё РѕР±С‰РµРµ РєРѕР»-РІРѕ РїРѕРїС‹С‚РѕРє РѕС‚ СЌС‚РѕРіРѕ IP, Р·Р°С„РёРєСЃРёСЂРѕРІР°РЅРЅС‹С… РІ ip_logs (РµСЃР»Рё РѕРЅРё Р±С‹Р»Рё)
if [ "$COUNT_ALL" > 0 ]; then 
echo -e "Total number of this attempts that have been recorded previously at this server ($SERVER)[$IP]: $COUNT_ALL \n\n"
fi
echo -e "====

This message was sent automatically by ValueHost security system.
Yor e-mail address obtained from the public WhoIs services.
We are sorry for disturb if you have received this message by mistake.
Please contact us if your e-mail is not relevant to this IP-address or network. 

====

Thank you,

Valuehost abuse team

http://www.valuehost.ru
+7 (812) 313-29-08,
+7 (495) 540-52-24
E-mail: abuse@valuehost.ru"
)"

# РїСЂРѕРІРµСЂСЏРµРј, РЅРµ РїРёСЃР°Р»Рё Р»Рё РјС‹ СѓР¶Рµ СЃРµРіРѕРґРЅСЏ Р°Р±СѓР·Сѓ РЅР° СЌС‚РѕС‚ IP
if [ "$(cat ~/abuse_logs/$DATE/abuse_noticed.lst | grep -c $n)" = "$(echo 0)" ]; then
    # РїСЂРѕРІРµСЂСЏРµРј РЅР°Р»РёС‡РёРµ Р°РґСЂРµСЃР° РґР»СЏ РѕС‚РїСЂР°РІРєРё Р°Р±СѓР·С‹
    if [ "$EMAIL" = "$(echo "")" ]; then
    # РµСЃР»Рё Р°РґСЂРµСЃ РЅРµ РЅР°Р№РґРµРЅ, С‚Рѕ РѕС‚РїСЂР°РІР»СЏРµРј РїРёСЃСЊРјРѕ РјРЅРµ
    (echo -e "${MAIL_BODY}") | mail -s "oops, IP $n has no abuse e-mail" mkotikov@yandex.ru
  else
    # РµСЃР»Рё Р°РґСЂРµСЃ РµСЃС‚СЊ - РїРёС€РµРј РЅР° Р°РґСЂРµСЃ Рё РґСѓР±Р»РёСЂСѓРµРј РјРЅРµ (#+ СѓРІРµРґРѕРјР»СЏРµРј РјРµРЅСЏ, С‡С‚Рѕ Р°РґСЂРµСЃ СѓРІРµРґРѕРјР»РµРЅ) + РґРµР»Р°РµРј Р·Р°РїРёСЃСЊ РІ Р»РѕРі РѕС‚РїСЂР°РІРєРё СѓРІРµРґРѕРјР»РµРЅРёР№
    (echo -e "From:abuse@valuehost.ru\nSubject:Mass bruteforce attemps from your network: IP $n\nTo:mkotikov@yandex.ru, $EMAIL" ; 
    echo -e "${MAIL_BODY}") | sendmail -t "mkotikov@yandex.ru, $EMAIL" ; 
#   echo -e "From:abuse@valuehost.ru\nSubject:abuse notice for $n was sent to $EMAIL from $SERVER\nTo:mkotikov@yandex.ru\nReport from $SERVER: $EMAIL noticed about $n" | sendmail -t mkotikov@yandex.ru ; 
    echo "$EMAIL noticed about $n at $DATE $TIME" >> ~/abuse_logs/$DATE/abuse_noticed.lst
  fi
else
  # Р° РµСЃР»Рё СѓР¶Рµ РїРёСЃР°Р»Рё - РЅРёС‡РµРіРѕ РЅРµ РґРµР»Р°РµРј
  sleep 1
fi
);
done;
